using System.Data;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;

namespace ffnotev2.Dialogs;

public partial class TableEditorDialog : Window
{
    private readonly DataTable _dt = new();

    public TableEditorDialog(string markdownTable)
    {
        InitializeComponent();
        ParseMarkdownToDataTable(markdownTable);
        Grid.ItemsSource = _dt.DefaultView;
    }

    /// <summary>OK 시 산출된 마크다운 표(개행으로 종료).</summary>
    public string ResultMarkdown { get; private set; } = string.Empty;

    private void ParseMarkdownToDataTable(string md)
    {
        var lines = (md ?? string.Empty)
            .Split('\n')
            .Select(l => l.TrimEnd('\r'))
            .Where(l => l.Length > 0 && l[0] == '|' && l[^1] == '|')
            .ToList();
        if (lines.Count == 0)
        {
            _dt.Columns.Add("열1");
            _dt.Columns.Add("열2");
            return;
        }

        // 첫 행 = 헤더
        var headerCells = SplitCells(lines[0]);
        foreach (var (cell, idx) in headerCells.Select((c, i) => (c, i)))
        {
            var baseName = string.IsNullOrEmpty(cell) ? $"열{idx + 1}" : cell;
            _dt.Columns.Add(UniqueColumnName(baseName));
        }

        int dataStart = (lines.Count > 1 && IsSeparator(lines[1])) ? 2 : 1;
        for (int i = dataStart; i < lines.Count; i++)
        {
            if (IsSeparator(lines[i])) continue;
            var cells = SplitCells(lines[i]);
            var row = _dt.NewRow();
            for (int j = 0; j < _dt.Columns.Count && j < cells.Length; j++)
                row[j] = cells[j];
            _dt.Rows.Add(row);
        }
    }

    private string UniqueColumnName(string baseName)
    {
        if (!_dt.Columns.Contains(baseName)) return baseName;
        for (int i = 2; ; i++)
        {
            var n = $"{baseName}_{i}";
            if (!_dt.Columns.Contains(n)) return n;
        }
    }

    private void Grid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        // 모든 컬럼을 텍스트 편집 가능하게 + 기본 폭 부여
        if (e.Column is DataGridTextColumn tc)
        {
            tc.MinWidth = 60;
        }
    }

    private void Grid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        // 컬럼 자동 생성 직후 — 필요시 확장
    }

    /// <summary>사용자가 드래그로 바꾼 컬럼 순서(DisplayIndex)는 DataGrid에만 반영되고
    /// DataTable 순서는 그대로다. RebindGrid가 DataTable 순서로 컬럼을 재생성하므로
    /// 구조 변경(추가/삭제/이름변경/확인) 직전에 화면 순서를 DataTable에 먼저 반영해
    /// 기존 열 위치가 흐트러지지 않게 한다.</summary>
    private void SyncColumnOrderFromGrid()
    {
        if (Grid.Columns.Count == 0) return;
        var ordered = Grid.Columns
            .OrderBy(c => c.DisplayIndex)
            .Select(c => c.Header?.ToString())
            .Where(h => !string.IsNullOrEmpty(h) && _dt.Columns.Contains(h!))
            .ToList();
        for (int i = 0; i < ordered.Count; i++)
            _dt.Columns[ordered[i]!]!.SetOrdinal(i);
    }

    /// <summary>DataGrid는 바인딩된 DataTable의 컬럼 컬렉션 변경 시 자동으로 컬럼을
    /// 재생성하지 않는다. 컬럼 추가/삭제/이름변경 후 ItemsSource를 다시 걸어 강제 재생성.</summary>
    private void RebindGrid()
    {
        Grid.CommitEdit(DataGridEditingUnit.Cell, true);
        Grid.CommitEdit(DataGridEditingUnit.Row, true);
        _targetCol = null;  // 재생성으로 기존 컬럼 객체 무효
        Grid.ItemsSource = null;
        Grid.ItemsSource = _dt.DefaultView;
    }

    // −열 삭제 대상 컬럼. 헤더 클릭으로 지정. RebindGrid 시 컬럼 객체가 새로 생성되므로 무효화.
    private DataGridColumn? _targetCol;

    // 헤더 단일 클릭 → 그 열 전체 선택 + 삭제 대상으로 기억. e.Handled을 세팅하지 않아
    // 컬럼 리오더 드래그/더블클릭(이름 변경)과 공존한다.
    private void Grid_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (FindHeader(e.OriginalSource)?.Column is DataGridColumn col)
            SelectColumn(col);
    }

    private void SelectColumn(DataGridColumn col)
    {
        _targetCol = col;
        Grid.SelectedCells.Clear();
        DataGridCellInfo firstCell = default;
        bool any = false;
        foreach (var item in Grid.Items)
        {
            if (item is not System.Data.DataRowView) continue;
            var ci = new DataGridCellInfo(item, col);
            Grid.SelectedCells.Add(ci);
            if (!any) { firstCell = ci; any = true; }
        }
        if (any) Grid.CurrentCell = firstCell;
    }

    private static DataGridColumnHeader? FindHeader(object? src)
    {
        DependencyObject? d = src as DependencyObject;
        while (d is not null)
        {
            if (d is DataGridColumnHeader h) return h;
            d = ffnotev2.Services.VisualTreeWalker.GetAnyParent(d);
        }
        return null;
    }

    // 컬럼 헤더 더블클릭으로 이름 변경. EventSetter+PreviewMouseLeftButtonDown 방식은
    // CanUserReorderColumns=True에서 첫 클릭이 리오더 드래그로 마우스를 캡처해
    // 두 번째 클릭의 ClickCount==2가 같은 헤더 핸들러에 도달하지 못해 깨졌음.
    // DataGrid 레벨의 PreviewMouseDoubleClick(터널)로 받아 헤더를 hit-test.
    private void Grid_PreviewMouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        var header = FindHeader(e.OriginalSource);
        if (header is null) return;
        if (header.Column is not DataGridColumn col) return;
        e.Handled = true;
        SyncColumnOrderFromGrid();
        var current = col.Header?.ToString() ?? string.Empty;
        var dlg = new RenameDialog(current) { Owner = this, Title = "컬럼 이름 변경" };
        if (dlg.ShowDialog() != true) return;
        var newName = dlg.EnteredName;
        if (string.IsNullOrWhiteSpace(newName) || newName == current) return;
        if (_dt.Columns.Contains(newName))
        {
            MessageBox.Show(this, "같은 이름의 컬럼이 이미 있습니다.", "표 편집",
                MessageBoxButton.OK, MessageBoxImage.Warning);
            return;
        }
        if (_dt.Columns.Contains(current))
        {
            _dt.Columns[current]!.ColumnName = newName;
            RebindGrid();
        }
    }

    private void AddRow_Click(object sender, RoutedEventArgs e)
    {
        _dt.Rows.Add(_dt.NewRow());
    }

    private void DeleteRow_Click(object sender, RoutedEventArgs e)
    {
        Grid.CommitEdit(DataGridEditingUnit.Cell, true);
        Grid.CommitEdit(DataGridEditingUnit.Row, true);

        // SelectionUnit=CellOrRowHeader라 셀만 클릭하면 SelectedItems가 비고
        // SelectedCells만 채워진다. 행 헤더/셀/현재 셀 모두에서 행을 모은다.
        var rows = new List<DataRowView>();
        void Add(object? item)
        {
            if (item is DataRowView rv && !rows.Contains(rv)) rows.Add(rv);
        }

        foreach (var item in Grid.SelectedItems) Add(item);
        foreach (var cell in Grid.SelectedCells) Add(cell.Item);
        if (rows.Count == 0) Add(Grid.CurrentCell.Item);

        foreach (var rv in rows)
        {
            if (rv.Row.RowState != DataRowState.Detached
                && rv.Row.RowState != DataRowState.Deleted)
                _dt.Rows.Remove(rv.Row);
        }
    }

    private void AddCol_Click(object sender, RoutedEventArgs e)
    {
        SyncColumnOrderFromGrid();
        var defaultName = $"열{_dt.Columns.Count + 1}";
        var dlg = new RenameDialog(defaultName) { Owner = this, Title = "새 컬럼 이름" };
        if (dlg.ShowDialog() != true) return;
        var name = dlg.EnteredName;
        if (string.IsNullOrWhiteSpace(name)) name = defaultName;
        if (_dt.Columns.Contains(name))
        {
            MessageBox.Show(this, "같은 이름의 컬럼이 이미 있습니다.", "표 편집",
                MessageBoxButton.OK, MessageBoxImage.Warning);
            return;
        }
        _dt.Columns.Add(name);
        RebindGrid();
    }

    private void DeleteCol_Click(object sender, RoutedEventArgs e)
    {
        SyncColumnOrderFromGrid();
        // 헤더 클릭으로 지정한 열 → 현재 셀의 열 → (지정 없으면) 마지막 열 순으로 대상 결정
        DataGridColumn? target = _targetCol;
        if (target is null && Grid.CurrentCell.IsValid) target = Grid.CurrentCell.Column;
        if (target is null && Grid.Columns.Count > 0) target = Grid.Columns[^1];
        if (target is null) return;
        var name = target.Header?.ToString();
        if (string.IsNullOrEmpty(name) || !_dt.Columns.Contains(name)) return;

        var confirm = MessageBox.Show(this,
            $"'{name}' 컬럼을 삭제할까요? 모든 행의 해당 값이 사라집니다.",
            "표 편집", MessageBoxButton.OKCancel, MessageBoxImage.Warning);
        if (confirm != MessageBoxResult.OK) return;

        _dt.Columns.Remove(name);
        RebindGrid();
    }

    private void Confirm_Click(object sender, RoutedEventArgs e)
    {
        Grid.CommitEdit(DataGridEditingUnit.Cell, true);
        Grid.CommitEdit(DataGridEditingUnit.Row, true);
        SyncColumnOrderFromGrid();
        ResultMarkdown = BuildMarkdown();
        DialogResult = true;
        Close();
    }

    private string BuildMarkdown()
    {
        if (_dt.Columns.Count == 0) return string.Empty;
        var sb = new StringBuilder();
        sb.Append('|');
        foreach (DataColumn col in _dt.Columns)
            sb.Append(' ').Append(SanitizeCell(col.ColumnName)).Append(" |");
        sb.Append('\n').Append('|');
        foreach (DataColumn _ in _dt.Columns) sb.Append("---|");
        sb.Append('\n');

        foreach (DataRow row in _dt.Rows)
        {
            if (row.RowState == DataRowState.Deleted) continue;
            sb.Append('|');
            foreach (DataColumn col in _dt.Columns)
            {
                var val = row[col]?.ToString() ?? string.Empty;
                sb.Append(' ').Append(SanitizeCell(val)).Append(" |");
            }
            sb.Append('\n');
        }
        return sb.ToString();
    }

    // 셀 안의 '|'와 개행은 마크다운 표를 깨므로 공백으로 치환
    private static string SanitizeCell(string s) =>
        s.Replace('\r', ' ').Replace('\n', ' ').Replace('|', ' ').Trim();

    private static string[] SplitCells(string row)
    {
        if (row.Length < 2 || row[0] != '|' || row[^1] != '|') return new[] { row.Trim() };
        var inner = row.Substring(1, row.Length - 2);
        return inner.Split('|').Select(s => s.Trim()).ToArray();
    }

    private static bool IsSeparator(string line)
    {
        if (line.Length < 3 || line[0] != '|' || line[^1] != '|') return false;
        foreach (var c in line) if (c != '|' && c != '-' && c != ':' && c != ' ') return false;
        return line.Contains('-');
    }
}
